# Practice Excercise Questions

# Question 1

**Create a NumPy array of 10 random integers between 0 and 100, and print the array to the console.**

In [ ]:
import numpy as np
input_list=[]
for i in range(0,10):
  arr=np.random.randint(0,100)
  input_list.append(arr)
  i+=1

output=np.array(input_list)
print(output)
print(type(output))

[ 9 78 86 26 85 58 67 69 10 49]
<class 'numpy.ndarray'>


# Question 2

Create a 2D NumPy array of size 3x3, with each element initialized to the value 5.0, and print the array to the console.

In [ ]:
arr=np.ones((3,3))
arr=arr*5.0
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


# Question 3

Create a NumPy array of 10 equally spaced values between 0 and 1, and print the array to the console.

In [ ]:
a=np.linspace(0 , 1 , 10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# Question 4

Create a NumPy array of 20 values between -1 and 1, spaced at irregular intervals using a sine function, and print the array to the console.

In [ ]:
a=np.linspace(-np.pi,np.pi,20)
b=np.sin(a)

print(b)

[-1.22464680e-16 -3.24699469e-01 -6.14212713e-01 -8.37166478e-01
 -9.69400266e-01 -9.96584493e-01 -9.15773327e-01 -7.35723911e-01
 -4.75947393e-01 -1.64594590e-01  1.64594590e-01  4.75947393e-01
  7.35723911e-01  9.15773327e-01  9.96584493e-01  9.69400266e-01
  8.37166478e-01  6.14212713e-01  3.24699469e-01  1.22464680e-16]


# Question 5

Create a 3D NumPy array of size 3x3x3, with each element initialized to a random integer between 0 and 9, and print the array to the console.

In [ ]:
array_list=[]
for i in range(0,27):
  arr=np.random.randint(0,9)
  array_list.append(arr)

array_list=np.array(array_list).reshape((3,3,3))
print(array_list)

[[[6 6 5]
  [4 7 7]
  [8 4 6]]

 [[0 3 3]
  [7 3 0]
  [3 8 4]]

 [[6 6 4]
  [6 0 1]
  [6 1 7]]]


# Question 6

Create a 2D NumPy array of size 4x4, with each row containing the values 1, 2, 3, and 4, respectively, and print the array to the console.

In [ ]:
arr=[1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4]
arr=np.array(arr).reshape(4,4)
print(arr)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
my_array = np.tile([1, 2, 3, 4], (4, 1))
print(my_array)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# Question 7

Create a NumPy array of 10 random integers between 0 and 100, and then sort the array in descending order, and print the sorted array to the console.

In [ ]:
my_list=[]
for i in range(0,10):
  my_array=np.random.randint(0,100)
  my_list.append(my_array)

my_list.sort(reverse=True)
my_list=np.array(my_list)
print(my_list)

[96 90 86 74 58 41 41 18 14  0]


# Question 8

Create a NumPy array of 5 values between 0 and 1, and then round the values to 2 decimal places, and print the rounded array to the console.

In [ ]:
arr=np.linspace(0,1 ,5)
for i in range(0,5):
  arr[i]=round(arr[i], 2)
  i+=1
print(arr)

[0.   0.25 0.5  0.75 1.  ]


# Question 9

Create a 2D NumPy array of size 5x5, with each element initialized to a random integer between 0 and 9. Then, extract the diagonal elements of the array, and print them to the console.

In [ ]:
my_list=[]
for i in range(0,25):
  arr=np.random.randint(0,9)
  my_list.append(arr)

my_list=np.diag(np.array(my_list).reshape(5,5))
print(my_list)

[4 2 8 1 1]


# Question 10

Create a 2D NumPy array of size 5x5, with each element initialized to a random integer between 0 and 9. Then, calculate the sum, mean, and standard deviation of the elements in each row of the array, and print the results to the console.

In [ ]:
my_list=[]
means=[]
sums=[]
stds=[]

for i in range(0,25):
  arr=np.random.randint(0,9)
  my_list.append(arr)

my_list=np.array(my_list).reshape(5,5)
for i in range(0,len(my_list)):
  mean=my_list[i].mean()
  means.append(mean)
  sum=my_list[i].sum()
  sums.append(sum)
  std=my_list[i].std()
  stds.append(std)



print('Means Row By Row=' , means)
print('Sum row by row ='  , sums)
print('std row by row =' , stds)

Means Row By Row= [3.4, 3.0, 4.4, 2.2, 1.6]
Sum row by row = [17, 15, 22, 11, 8]
std row by row = [2.33238075793812, 1.4142135623730951, 3.261901286060018, 2.039607805437114, 1.3564659966250536]
